const $ = (s) => document.querySelector(s);
const services = {
  web:{kicker:'01 — PRODUCTO DIGITAL',title:'Desarrollo web',lead:'Diseñamos plataformas rápidas, claras y preparadas para crecer junto con tu negocio.',number:'01',label:'WEB SYSTEMS',foot:'De la estrategia al código: creamos productos digitales que resuelven necesidades reales.',drawer:'Capacidades web',list:['Sitios y e-commerce','Aplicaciones web a medida','UX / UI y prototipado','APIs y automatización']},
  data:{kicker:'02 — ARQUITECTURA',title:'Bases de datos',lead:'Transformamos información dispersa en una fuente confiable para tu operación.',number:'02',label:'DATA ARCHITECTURE',foot:'Organizamos, protegemos y conectamos el activo más valioso de tu empresa: sus datos.',drawer:'Capacidades de datos',list:['Modelado y normalización','Migración de información','Dashboards y reportes','Backups y seguridad']},
  access:{kicker:'03 — SEGURIDAD FÍSICA',title:'Control de acceso',lead:'Integramos personas, espacios y reglas en una operación segura y visible.',number:'03',label:'ACCESS CONTROL',foot:'Controla entradas, horarios y permisos con una solución conectada a tu negocio.',drawer:'Capacidades de acceso',list:['Biométricos y lectores','Control de visitantes','Reportes en tiempo real','Integración con nómina']},
  pos:{kicker:'04 — COMERCIO CONECTADO',title:'Punto de venta',lead:'Una caja ágil y una operación ordenada, desde el inventario hasta el último ticket.',number:'04',label:'POS ECOSYSTEM',foot:'Centraliza ventas, clientes e inventario para que tu equipo pueda enfocarse en atender.',drawer:'Capacidades de punto de venta',list:['Ventas e inventario','Facturación y cortes','Multi-sucursal','CRM y lealtad']}
};
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');window.scrollTo(0,0)}
document.querySelectorAll('.service-trigger').forEach(btn=>btn.addEventListener('click',()=>{const d=services[btn.dataset.service];$('#detailKicker').textContent=d.kicker;$('#detailTitle').textContent=d.title;$('#detailLead').textContent=d.lead;$('#detailNumber').textContent=d.number;$('#detailLabel').textContent=d.label;$('#detailFoot').textContent=d.foot;$('#drawerTitle').textContent=d.drawer;$('#drawerList').innerHTML=d.list.map(x=>`<li>${x}</li>`).join('');show('detail')}));
document.querySelectorAll('.back-home').forEach(b=>b.addEventListener('click',()=>show('inicio')));$('#backButton').addEventListener('click',()=>show('inicio'));$('#aboutButton').addEventListener('click',()=>show('about'));$('#faqButton').addEventListener('click',()=>show('faq'));
$('#moreButton').addEventListener('click',()=>{$('#infoDrawer').classList.add('open');$('#infoDrawer').setAttribute('aria-hidden','false')});$('#closeDrawer').addEventListener('click',()=>{$('#infoDrawer').classList.remove('open');$('#infoDrawer').setAttribute('aria-hidden','true')});
const modal=$('#contactModal');function openModal(){modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$('#heroContact').addEventListener('click',openModal);$('#detailContact').addEventListener('click',openModal);document.querySelectorAll('.about-contact').forEach(x=>x.addEventListener('click',openModal));$('#closeModal').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
let slide=0;const slides=document.querySelectorAll('.slide'),dots=document.querySelectorAll('.slider-dots b');setInterval(()=>{slides[slide].classList.remove('active');dots[slide].classList.remove('active');slide=(slide+1)%slides.length;slides[slide].classList.add('active');dots[slide].classList.add('active');$('#slideCount').textContent=`0${slide+1} / 03`},3800);dots[0].classList.add('active');
