const $ = (s) => document.querySelector(s);
const services = {
  web: { kicker: '01 — PRODUCTO DIGITAL', title: 'Desarrollo web', lead: 'Diseñamos plataformas rápidas, claras y preparadas para crecer junto con tu negocio.', number: '01', label: 'WEB SYSTEMS', foot: 'De la estrategia al código: creamos productos digitales que resuelven necesidades reales.', drawer: 'Servicios web', list: ['Sitios y e-commerce', 'Aplicaciones web a medida', 'UX / UI y prototipado', 'APIs y automatización'], images: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=700&q=85', 'https://images.unsplash.com/photo-1555099962-4199c345e5dd?auto=format&fit=crop&w=700&q=85'], alts: ['Código de una aplicación web', 'Diseñador desarrollando una web', 'Pantalla con código'] },
  data: { kicker: '02 — ARQUITECTURA', title: 'Bases de datos', lead: 'Transformamos información en un sistema ordenado y estructurado, para que tengas el control de todo en tu empresa.', number: '02', label: 'DATA ARCHITECTURE', foot: 'Organizamos, protegemos y conectamos el activo más valioso de tu empresa: sus datos.', drawer: 'Servicios de bases de datos', list: ['Modelado y normalización', 'Migración de información', 'Dashboards y reportes', 'Backups y seguridad'], images: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1543286386-713bdd548da4?auto=format&fit=crop&w=700&q=85', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=700&q=85'], alts: ['Tablero de datos', 'Visualización de métricas', 'Analítica de negocio'] },
  access: { kicker: '03 — SEGURIDAD FÍSICA', title: 'Control de acceso', lead: 'Integramos personas, espacios y reglas en una operación segura y visible.', number: '03', label: 'ACCESS CONTROL', foot: 'Controla entradas, horarios y permisos con una solución conectada a tu negocio.', drawer: 'Servicios  de control de acceso', list: ['Biométricos y lectores', 'Control de visitantes', 'Reportes en tiempo real', 'Integración con nómina'], images: ['https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=700&q=85', 'https://images.unsplash.com/photo-1633265486064-086b219458ec?auto=format&fit=crop&w=700&q=85'], alts: ['Acceso seguro a un edificio', 'Tecnología de seguridad', 'Cerradura inteligente'] },
  pos: { kicker: '04 — COMERCIO CONECTADO', title: 'Punto de venta', lead: 'Una caja ágil y una operación ordenada, desde el inventario hasta el último ticket.', number: '04', label: 'POS ECOSYSTEM', foot: 'Centraliza ventas, clientes e inventario para que tu equipo pueda enfocarse en atender.', drawer: 'Servicios de punto de venta', list: ['Ventas e inventario', 'Facturación y cortes', 'Multi-sucursal', 'CRM y lealtad'], images: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=700&q=85', 'https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=700&q=85'], alts: ['Pago con terminal', 'Compra con tarjeta', 'Tienda moderna'] }
};
let currentScreen = $('#inicio'), isChanging = false;
function show(id) { if (isChanging || currentScreen.id === id) return; isChanging = true; const next = $('#' + id), wipe = $('#pageTransition'); wipe.classList.add('run'); setTimeout(() => { currentScreen.classList.remove('active'); next.classList.add('active'); currentScreen = next; window.scrollTo(0, 0) }, 260); setTimeout(() => { wipe.classList.remove('run'); isChanging = false }, 820) }
function populateCollage(d) { const imageIds = ['collageMain', 'collageTop', 'collageBottom']; imageIds.forEach((id, index) => { $('#' + id).src = d.images[index]; $('#' + id).alt = d.alts[index] }) }
document.querySelectorAll('.service-trigger').forEach(btn => btn.addEventListener('click', () => { const d = services[btn.dataset.service]; btn.classList.add('is-selected'); setTimeout(() => btn.classList.remove('is-selected'), 650); $('#detailKicker').textContent = d.kicker; $('#detailTitle').textContent = d.title; $('#detailLead').textContent = d.lead; $('#detailNumber').textContent = d.number; $('#detailLabel').textContent = d.label; $('#detailFoot').textContent = d.foot; $('#drawerTitle').textContent = d.drawer; $('#drawerList').innerHTML = d.list.map(x => `<li>${x}</li>`).join(''); populateCollage(d); show('detail') }));
document.querySelectorAll('.back-home').forEach(b => b.addEventListener('click', () => show('inicio'))); $('#backButton').addEventListener('click', () => show('inicio')); $('#aboutButton').addEventListener('click', () => show('about')); $('#faqButton').addEventListener('click', () => show('faq'));
$('#moreButton').addEventListener('click', () => { $('#infoDrawer').classList.add('open'); $('#infoDrawer').setAttribute('aria-hidden', 'false') }); $('#closeDrawer').addEventListener('click', () => { $('#infoDrawer').classList.remove('open'); $('#infoDrawer').setAttribute('aria-hidden', 'true') });
const modal = $('#contactModal'); function openModal() { modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false') } function closeModal() { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true') } $('#heroContact').addEventListener('click', openModal); $('#detailContact').addEventListener('click', openModal); document.querySelectorAll('.about-contact').forEach(x => x.addEventListener('click', openModal)); $('#closeModal').addEventListener('click', closeModal); modal.addEventListener('click', e => { if (e.target === modal) closeModal() });
let slide = 0; const slides = document.querySelectorAll('.slide'), dots = document.querySelectorAll('.slider-dots b'); setInterval(() => { slides[slide].classList.remove('active'); dots[slide].classList.remove('active'); slide = (slide + 1) % slides.length; slides[slide].classList.add('active'); dots[slide].classList.add('active'); $('#slideCount').textContent = `0${slide + 1} / 03` }, 3800); dots[0].classList.add('active');
